### ISSUE TITLE
[REQUEST] Add support for more plantables mod

### ISSUE THREAD

**Issue by gleitoncampos** [nopetrides/modding#4]
Hello!!
Thanks for your work! I don't know if it's possible, but will be very great to this mod work with more plantables like "[PlantEverything](https://valheim.thunderstore.io/package/Advize/PlantEverything/)"

Thanks for your attention!

**Comment by nopetrides** [comment]
Hey @gleitoncampos,

I can look into it. Need to learn about cross-compatibility with mods. I'll need to look into if it will need to make a separate version like "CropUtils for PlantEverything" or if there is a way a single version can support both with and without PE.

Thanks for the suggestion.

**Comment by nopetrides** [comment]
@gleitoncampos Give 1.2.1 a try. It is PlantEverything compatible. I went for a solution that is mod agnostic, so the mod should now work with any planting mod. I testing with PE, and it works as intended.

Be sure to run the game after installing the update, then enable Mod Computability Mode in the Config file.

![image](https://user-images.githubusercontent.com/22615608/210321058-5e727f80-fbe3-480d-aaef-4192509acf74.png)

You can then use the - and = keyboard keys to change the spacing between crops. For PE, crops are 0.5 (the default) and saplings are 2.0.

Just for clarity, I couldn't create the vanilla functionality for PE because the mod creator uses custom classes and the <Plant> class is not available during ghost placement, making the growth radius unknown. In order to know the growth radius I would need specific references to the PE mod and it's specific classes which would create an undesirable dependency.

I hope this is sufficient, let me know if you have any other suggestions.
